# Generated by Django 5.0.2 on 2024-03-06 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='products/audio/'),
        ),
    ]
